### ISSUE TITLE
Crashes when used on dedicated server

### ISSUE THREAD

**Issue by TeetoKaziim** [ryoryo25/TemporaryBlock#1]
Crash report

https://gist.github.com/TeetoKaziim/38bf06d60a4190e04139cdd78a40f3f7

Mod is referencing net/minecraft/client classes in the dedicated server, which is a place where these classes do not exist.

Forge Version: 14.23.5.2854
TemporaryBlock version: 1.0.2

Thank you for your time and efforts. The mod is pretty great.

**Comment by ryoryo25** [comment]
Thank you for your report!
Does the crash occur with only PolishedLib and TemporaryBlock?

**Comment by TeetoKaziim** [comment]
Yes, crash report with only those 2 mods (and forge): https://gist.github.com/TeetoKaziim/83eb674afc1ee4972efa9f6fa927274a

The mod works perfectly in singleplayer, this only happens in a server environment.

**Comment by ryoryo25** [comment]
OK, I'll try to find the cause.

**Comment by ryoryo25** [comment]
Sorry for the late reply.
I found out that the problem is the implementation of PolishedLib.
I'm trying to fix it now, so please wait for a while.
